### ISSUE TITLE
Decouple DB

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#10]
To reduce download times, add a method to check db version and add implementation in program to block progress until a database is available, else download in background and replace on next load (warn user from closing app if it's downloading).

**Comment by Harjot1Singh** [comment]
Is the database automatically downloaded by Core? Or is this only in the electron app?

If the latter, I suggest that the core should automatically download and update the DB as necessary (as well as itself), rather than the electron wrapper handling this.

**Comment by bhajneet** [comment]
@Harjot1Singh Is this fixed in dev? Do we download db to a user folder (like AppData on Windows)?

**Comment by Harjot1Singh** [comment]
We distribute the DB as a standard module, and for updates, (will) do effectively the same process npm does for updating packages, on `@shabados/database`

**Comment by bhajneet** [comment]
So long as updating Shabad OS will not invoke a re-download of the database package, close the issue if it's done in dev branch

**Comment by Harjot1Singh** [comment]
It'd probably have to re-download the database package for now if the entire application is updated
