### ISSUE TITLE
Dev Release Channel

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#105]
Be great for those who'd like to opt-in to beta changes :)

**Comment by bhajneet** [comment]
@Harjot1Singh this is the only issue I can see for beta/alpha release toggle in settings. I recall you saying there already is a toggle present in dev build. If so, then can we close this issue or is there something else remaining?

**Comment by Harjot1Singh** [comment]
I would have to check, but I'm fairly certain it got implemented.

**Comment by Harjot1Singh** [comment]
Confirmed
