### ISSUE TITLE
Position lost in banis for same session

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#114]
Example: Asa Ki Vaar. Shabad. Go back to Asa Ki Vaar. Position lost.

**Comment by Harjot1Singh** [comment]
I did not know that positions within the same session for the same Bani(/shabad) need to be stored?

**Comment by bhajneet** [comment]
Yes they do. Main lines as well for shabads. There are many jumps during kirtan and this helps keep/find your positions in different banis/shabads. It would also help to remember which lines in a shabad have been read for clarity as well.

**Comment by Sarabveer** [comment]
This is very important. It was a well received feature by users.

**Comment by Harjot1Singh** [comment]
To clarify:

1) Clicking on a Bani in History or Bookmarks will restore it to the previous position
2) Clicking on a Shabad in search will store that line in history and never be updated (aka store the searched line in History)
3) Clicking on a searched line/Shabad in History will jump back to whatever the actual last viewed line in the Shabad is

OR
2) Clicking on a shabad will store that line in history
3) History for the current shabad will always be updated to sync with the current line in the Shabad
