### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#116]
![image 3](https://user-images.githubusercontent.com/14130567/52907572-362a3480-3232-11e9-9191-ee3aac7b9f11.png)

Harjot says there is an issue with react-hotkeys. I'm simply posting the image for him.

**Comment by Harjot1Singh** [comment]
@bhajneet can you remind me how to reproduce?

**Comment by Harjot1Singh** [comment]
Open Shabad OS. This is considered main display. Dock on left.

Open Firefox and do your GUI workaround for a controller. Dock on right.
Doing a search on the right will make Shabad OS go white
There are no hotkeys to fix it
This is also assuming that Shabad OS had a controller open
Not sure if last bit matters

**Comment by Harjot1Singh** [comment]
Problem: hotkeys are not remounted when another controller changes another controller's shabad
