### ISSUE TITLE
Fix hotkey combos

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#136]
Also quick double-tap isn't working correctly. It briefly highlights the n+2 line, then goes back to n+1. I assume this has to do with the key-delay that was implemented #122 

This should be showing the second line after the debounce time is up. I would have assumed debounce works as follows:

Each key press adds a 120ms timer for the user to do something. At the end of 120ms with no keys hit, activate line.

If 3 keys hit in the above scenario up this limit to 600ms.

This lets the user still do combos at a reasonable speed (double-tap down to catch up, up-spacebar from secondary rahao line, etc.)

**Comment by Harjot1Singh** [comment]
What's quick double tap? Do you mean that the controller is jumping back to the previous line? It might be because the server is broadcasting the new n+1 line, and the controller is receiving that/giving that priority

**Comment by Harjot1Singh** [comment]
You're correct about how debounce works - it does work like that, but I suspect the comment I made above is what's going on

**Comment by Harjot1Singh** [comment]
Does the issue still apply in the same way/need updating, after your testing @bhajneet?

**Comment by bhajneet** [comment]
It's working correctly in dev.
