### ISSUE TITLE
Fix high number of previous lines from crowding out current line

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#137]
A temporary fix would be set previous-lines max-height to 30-50%. A better fix would be to sticky-position current-line to the viewable screen and place previous-lines and next-lines accordingly around it.

**Comment by Harjot1Singh** [comment]
Why ya closed this one? Also, with the advent of `position: sticky`, this is entirely possible

**Comment by bhajneet** [comment]
I thought it was impossible lol

**Comment by bhajneet** [comment]
Sticky does not solve this, JS is required. Current implementation is okay for most use cases.
