### ISSUE TITLE
Improve performance of opening long shabads/banis

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#143]
See end of #92

**Comment by Harjot1Singh** [comment]
Long Banis (and probably Shabads) can take a few seconds to open. Perhaps there is a smarter/faster way of loading/streaming the data?

**Comment by Harjot1Singh** [comment]
At the very least, we probably want a loader to indicate something is happening, perhaps?

**Comment by Harjot1Singh** [comment]
With the advent of https://github.com/ShabadOS/database/pull/1345, opening should be considerably faster. Needs some further testing.

**Comment by Harjot1Singh** [comment]
tested in dev, appears to be working well.
