### ISSUE TITLE
Confirm Firewall settings on startup or include notice during installer to allow access

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#144]
This should help resolve the number one issue users have of not being able to connect with different devices.

**Comment by Harjot1Singh** [comment]
I've seen some apps able to automatically configure firewall settings themselves

**Comment by Harjot1Singh** [comment]
https://www.infernux.no/2019-02-22-securingwindowsserver31/

**Comment by bhajneet** [comment]
Already autoconfigures, presumably electron builder
