### ISSUE TITLE
Push Settings to different displays

### ISSUE THREAD

**Issue by bhajansweet** [ShabadOS/desktop#15]

**Comment by Harjot1Singh** [comment]
I believe it's more common use case to configure one display, and do this externally like the navigator, than to have different displays with different configurations.

**Comment by Harjot1Singh** [comment]
Yeah, there's lots of different things there. I just feel that this release should have some form of settings syncing, since I personally found it a pain to have to go back up on stage to adjust the display for the PC there, vs doing it from my mobile.

Is there something we could draw up for including as a minimum release?

**Comment by bhajneet** [comment]
How about if we make it so any laptop on the network can change the settings? That should be an easy one. For now we can use "Network Wifi Password" as a "PIN Code" of some sort.

@bhajansweet What do you think?

**Comment by Harjot1Singh** [comment]
Revisiting this idea as I'm working on settings: how about a toggle that allows the settings to be configured by other clients?

In our settings, there'll be local, local-private, and global settings in terms of permissions/categories under the hood

**Comment by bhajneet** [comment]
For now a toggle is fine. Most people don't even know they can affect the Shabad OS monitors. This will probably need to be re-visited once we have a mobile app and more users.

What is local vs local-private?

What will the user read for the setting of this toggle?

**Comment by Harjot1Singh** [comment]
Local = settings that only affect the current device's settings (but can be modified by others, if enabled)
Local-private = settings that can only ever be modified by the current device (e.g. the toggle to allow others)
Global/Server = settings like analytics that can only exist on the server

**Comment by bhajneet** [comment]
Another question -- How do you control which display of the host is being changed?

Host can currently have multiple display setups (So one projector can be multiple lines of gurbani, the other can be english translations, TV can be single frame, etc.)

If we can, it might be nice to set up "Scenes" and allow users to apply those to specific displays so they don't have to constantly set them all up separately each time. Then if you have a "scene" you can modify that directly.

This can also apply to OBS in case people want to set up multiple OBS scenes (live captions subtitles and separate full screen presentation during broadcasts).

**Comment by Harjot1Singh** [comment]
The way I was envisioning it is that you can click on each device name that's connected to the server (and is allowing their settings to be modified), and then see the same settings as you would for your own machine. These would appear under a "Other devices" option in settings, or similar.

In the case of multi-display-single-device setups, I think more work has to kinda be done to figure out how it'd actually work. Regarding scenes & multi-display-single-device setups I reckon should be a new/different feature. 

On second thoughts, maybe we could extend this feature to have each connected instance register themselves separately, and then abstract everything out as screens, as opposed to devices? Then the option would be "Other screens", and would show any connected window to the server.

**Comment by bhajneet** [comment]
If it's possible to register connected instances, then you could place each one under the connected devices name (as a tree perhaps). That would be pretty intuitive and powerful

**Comment by Harjot1Singh** [comment]
That's a good idea. Could we file this as a separate issue and link back?

**Comment by Harjot1Singh** [comment]
Done in dev 🤘
