### ISSUE TITLE
Number hotkeys should "activate" the line

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#151]
This is working correctly for navigator. However, in bookmarks or history, if one hits the number hotkey, then it simple selects/focuses the line. It does not actually activate it's function/"click it" as it did in v1 golang. Was this intended behavior in v2 for some reason?

**Comment by Harjot1Singh** [comment]
It was because I categorised navigation hotkeying in two ways: `clickOnPress` which means that any hotkey like up, down, numbers are either activated on press all the time (like in the navigator), or only focused.

The original behaviour can be implemented (but I think that it means the user has to learn different behaviour, thoughts?)

**Comment by bhajneet** [comment]
I think arrows and numbers should act the same.

If we want to allow different functionality there should be a toggle in options to activate without hitting enter

Might want different CSS to help user understand that

Default should require user to hit enter in controller.

Display hotkeys should just work as described in related issue.

**Comment by Harjot1Singh** [comment]
There is an issue when enabling the "pressOnKey" behaviour for arrow keys too - in menus, the arrow will become useless, as the option will force the next option to be selected

**Comment by bhajneet** [comment]
I think if the user is hitting a hotkey it's because they want to activate it. Maybe there can be a way to activate pseudo select mode so user can go scrolling around and then try random hotkeys? #237 

Other option is for these hotkeys to show a pseudo select around the item they've hotkeyed to and require enter. However this clashes with behavior in navigator. I think whatever we do they should both match at the least.

**Comment by bhajneet** [comment]
Closing in favor of #237
