### ISSUE TITLE
Change navigator icon

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#152]
In addition to "search, bookmarks, and history/timeline" there should be a fourth "navigator" icon. This also ties in with our new UI/UX for v3 down the road.

This way if the user switches to a search, bookmark, or history screen, they will always know a quick and easy way to get back to the navigatable lines.

**Comment by Harjot1Singh** [comment]
Should be there, bottom-right

**Comment by bhajneet** [comment]
Yes it is, please change it to 'vertical_split' icon so it is clearer that it is a controller for the projector (shows lines on left and projector on right in icon or at least it will be more obvious when switching to new UI that it is the icon for that).

Could also be renamed to "controller". If not now, then after UI change.

**Comment by Harjot1Singh** [comment]
I think we should keep the name as the navigator, since the rest of the window does the controlling too. I'll change the icon

**Comment by Harjot1Singh** [comment]
Looked into changing the icon - `vertical_split` is part of MUI icons which we've removed as a dependency. Have a font-awesome icon replacement that we could use?

**Comment by bhajneet** [comment]
@Harjot1Singh why did the merge not close this?
