### ISSUE TITLE
Add hotkeys to presenter window

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#153]
The up, down, page {up, down}, and other relevant hotkeys should work directly on the presenter if the user clicks on it. This way if they are in a search, bookmark, or history window for the controller they can still change lines easily for the presenter (which updates the navigator behind the scenes). Related to #152

**Comment by Harjot1Singh** [comment]
Hmm, that would imply that within the window, you have elements of focus, which I do not think is that intuitive or easy to show others. The user would then also have to use the mouse to refocus the controller in order to enact hotkeys there?

**Comment by bhajneet** [comment]
You can add pop up arrows to the display to show changing lines and a circular button for autoselect.

Yes, if they wanted to do something with the controller after focusing the display, naturally they'd have to click/focus/use a controller only hotkey

**Comment by Harjot1Singh** [comment]
I think you'd want to show focusing/defocusing of the controller somehow, but i'm not sure about whether it's a good idea to allow them to change the line while they're looking for something else when weighed against the downsides (defocusable controller/loss of click-free hotkeys).

What situation would one be moving the lines still, but looking for something else? Surely if they're looking for something else, it's because they haven't found it in the current Shabad/Bani?

**Comment by Harjot1Singh** [comment]
We can however add global hotkeys that work without the controller, if that was the original intention

**Comment by bhajneet** [comment]
Too many times I've seen people miss the next line in the same shabad.
Sometimes it's literally the proceeding line and even displayed at the
bottom of the projector, but they still go to the search screen.

Regardless, the main reason is, if the controller is hidden, one should
have a hotkey/GUI way to move the line up and down in a minimalistic way
for single-display users without having to show the controller.

To show defocus of controller, you can simply make it more opaque or make
all the text less contrasting with it's bg until focused again.

I'm not aware of why we'd lose click-less hotkeys. ctrl+/ for search
shouldn't do anything with the presenter, it should be a hotkey to focus
the controller to search. Is there some hotkey that is conflicting? In v1
for up and down arrows if user focused the presenter and hit up / down, we
simply re-focused the controller and sent up / down even though if it was
hidden.

**Comment by Harjot1Singh** [comment]
> We can however add global hotkeys that work without the controller, if that was the original intention

Is it ok to have these hotkeys work ONLY when the controller is minimised?

**Comment by bhajneet** [comment]
Yes that is acceptable

Please break global hotkeys into it's own issue, I'll expand and add it to a project as we see fit

**Comment by Harjot1Singh** [comment]
Todo
- [ ] Fix debounce by wrapping nested GlobalHotkeys correctly
- [ ] Fix navigation to next line of non-continuous line order IDs in Banis (see first few lines of TavPrasad)
