### ISSUE TITLE
Allow ctrl+c and ctrl+v in search

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#163]
A user would intuit that if they can type and highlight text that they can also probably copy it / manipulate with pasting. Would help with troubleshooting/testing and also with pasting the same word multiple times. For example: `ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਤੇਰੋ ਨਾਮੁ ॥` they would be able to copy the first word and paste it 3-5 times to find the result.

**Comment by bhajneet** [comment]
Ctrl+v is working. Ctrl+c is going to navigator. Should be Ctrl+g to go to naviGator, but we are currently using it temporarily for copying gurbani.

**Comment by bhajneet** [comment]
Fixed in release and next-release

**Comment by saihaj** [comment]
v2.7 and v2.8
