### ISSUE TITLE
Unify accent insertion/deletion in search bar

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#166]
Issues with inserting accent chars. My first guess would be the interpreter for unicode/ASCII in search causes accents to be placed differently. Backspace is not following the interpreter rule. So either use pure ASCII convention or pure Unicode convention for adding/removing accents.

Example: `#bi<backspace>`
Example: `#pRb vis` you'll see the `i` char go behind the `v` and then after typing the `s` it will go back even another char. Then try adding more chars or backspacing from here. It will keep going back another char.
Example: `#hm qy ki` (unicode style) or `#hm qy ik` (ascii style) should be showing the result `ਹਮ ਤੇ ਕਿਛੂ ਨ ਹੋਇ ਮੇਰੇ ਸ੍ਵਾਮੀ`

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/pull/161#issuecomment-500635936_

Child of #211

**Comment by Harjot1Singh** [comment]
Solution: only convert to ascii if entered text is not already ascii etc

**Comment by bhajneet** [comment]
Will be fixed by fixing "toAscii" function using "isGurbani" function. See discussion: https://github.com/ShabadOS/gurmukhi-utils/issues/140
