### ISSUE TITLE
Segregate home / end hotkeys in search

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#168]
Either highlight first and last results or move the insertion point of query to beginning and end. Do only one function with hotkey. Currently each hotkey does two things.

Child of #211

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/pull/161#issuecomment-500638754_

**Comment by Harjot1Singh** [comment]
Set it to be consistent with other controller views aka jump lines only
