### ISSUE TITLE
Fix incorrect highlighting of full word search results

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#170]
Incorrect highlighting. See first letter in results 3-5.

![image](https://user-images.githubusercontent.com/14130567/59235585-07104800-8bc0-11e9-91ff-db8477d6ac3f.png)

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/pull/161#issuecomment-500642906_

**Comment by bhajneet** [comment]
The entire word should be highlighted even if it's a partial match of the beginning.

Child of #211

**Comment by Jujhaar** [comment]
I can take this one.
