### ISSUE TITLE
Add descriptions to options in settings

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#175]
https://github.com/ShabadOS/desktop/blob/dev/app/frontend/src/lib/consts.js

@Harjot1Singh where/how on here can we add descriptions?

**Comment by Harjot1Singh** [comment]
E.g. Line 172, add a key called `description`.

Make sure you spread out the inline objects to have their properties on new lines

**Comment by bhajneet** [comment]
Duplicate of #115
