### ISSUE TITLE
webpage for live streaming

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#179]
An html webpage (`localhost:port/live`) with the necessary nesting of elements to allow custom CSS in a livestream program to affect what is shown and how it's styled, colored, sized, etc.

The alpha release of v2 does not require a live caption tool. This simple webpage with zero CSS would be good enough for all our clientele at this point since they only plug the custom CSS in one-time.

Just need to be sure the nesting of html elements is done in a way that allows for all CSS combos.

**Comment by Harjot1Singh** [comment]
Is preliminary larivaar support required?

**Comment by Harjot1Singh** [comment]
You can add a custom theme file under `%APPDATA%/Shabad OS/themes/[ThemeName].css`.

Then you can currently customise with `.overlay .line .gurmukhi` etc.

Note, it's re-using the same logic/component to render lines as the Presenter Display does, so am unaware of any unwanted side-affects

**Comment by bhajneet** [comment]
This should be treated as a very barebones html API of sorts.

There is currently too much CSS on the page which makes me wonder if it's coupled with the CSS of the presenter page. Basically if you can remove all CSS files from this page then it will work as intended allowing the end user to customize it once and leave it. (Any changes to the HTML/CSS would be considered a "breaking" change for livestreamers.) So best to not include any CSS from other sources, and allow them to choose their own fonts, sizes, positioning, padding, etc. This way (ideally) they will set it once and forget it regardless of what we do to presenter page.

Eventually we can create a live caption tool of sorts separate from Shabad OS that helps them customize this with a GUI, but even discussing that is a long ways ahead.

**Comment by Harjot1Singh** [comment]
It’s not coupled with the Presenter page, but it does set some of the styles for the lines that appear there.

I can retain the HTML structure but strip the CSS, if that’s suitable. The reason for reusing the Line component is because it already has the logic for producing larivaar, splitting words into vishraams etc, so I suspect it just needs some refactoring to make it more barebones

**Comment by Harjot1Singh** [comment]
We should potentially keep everything hidden by default, so that new additions do not break users' layout.
