### ISSUE TITLE
Default Fullscreen Mode

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#18]
There should be a way of setting the display window to fullscreen by default, hiding the menu. This is useful in the situation that core/desktop is installed on a laptop, and you just want to control it from a phone or laptop straight away.

**Comment by bhajneet** [comment]
Could you explain this a little more? As I understand you are asking for the ability to start the program in full screen with no navigator/controller being shown. If you're on windows and are automating the task you can use AutoHotKey to Ctrl+F and Ctrl+H after the window opens. It is not ideal, but perhaps we can look into improving this via native / gui options in the future.

**Comment by Harjot1Singh** [comment]
^^ as you've said. AHK is what I had planned to use, but it's obviously not ideal for Gurdwaras or non-technical users. I don't mind chucking in a PR if this project is still in active development.

**Comment by bhajneet** [comment]
It should not be too hard to add two options in settings:

1. Open in fullscreen
2. Hide controller on start

Would very much appreciate any PRs, already saw your dockerise request which I will look into later as I'm on vacation currently. Yes, this project is "active" and we are often thinking about improvements/overarching directions.

**Comment by Harjot1Singh** [comment]
Awesome. Is there anywhere that we can discuss general direction etc? Would love to suggest a few things, and give my feedback from a technical and user experience perspective.

**Comment by bhajneet** [comment]
Hi, your website gave a "mail server down" error. Please [send an email](https://github.com/ShabadOS) to the team with contact info.

**Comment by bhajneet** [comment]
Dev branch: Do we need to add gui options for "open in fullscreen" and "hide controller on start"?

If so, both options should be set to "true" by default

**Comment by Harjot1Singh** [comment]
Should the controller be hidden by default on start?

**Comment by bhajneet** [comment]
Yes, but not minimized

Same with titlebars or any other UI elements

Only thing that should be seen is a bg (by theme) and the title "Shabad OS" animation in the middle

**Comment by bhajneet** [comment]
Can rename "Hide controller on start" to "Hide UI on start"

**Comment by AkalUstat** [comment]
@bhajneet would this just be for the main window?

**Comment by bhajneet** [comment]
That would be a good start. Ultimately, it should apply to any "presenter" window that is opened on startup. Not sure what the spec is for #456. I would imagine that the "main window" is the full screen controller (which is different from this issue), and that the other displays would all be presenters, which if this issue's feature is toggled on would start up in full screen windows.

Goal is for a gurdwara to be able to start their "server/PC" without having to actually configure anything. They can then use their mobile devices / alternate PCs to control the projectors.

**Comment by AkalUstat** [comment]
@bhajneet  im testing this right now and if i set the fullscreen option to true, everything pops in fullscreen ( the app, settings, etc). Is this what we want?

**Comment by Harjot1Singh** [comment]
We only want the initial windows that are loaded onServerReady to be fullscreened

**Comment by AkalUstat** [comment]
Im not sure why other windows are also being full screened (settings etc) even mainWindow is only one

**Comment by Harjot1Singh** [comment]
You might be setting a global value. Make sure you instead iterate over `getDisplayWindows` export from `windows.js` and call `fullscreen` for each of those.

**Comment by AkalUstat** [comment]
it still doesnt exclude the settings for some reason...

**Comment by AkalUstat** [comment]
playing around with a workaround for mac rn
