### ISSUE TITLE
Hotkey for copying different segments of the activated line

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#188]
As a general comment, I think `cmd/ctrl + c` to copy the whole pangti, and sequences like `cmd/ctrl+c g` to copy segments of the pangti is probably the best solution.

With regards to customisable hotkeys, we store the configuration but have no way of updating the current hotkeys. We can create an issue for it to resolve later and it shouldn't be too hard since `react-hotkeys` now offers a `recordHotKey` function to make this easier.

_Originally posted by @Harjot1Singh in https://github.com/ShabadOS/desktop/issues/103#issuecomment-507322573_

This should affect whatever active line contains the info, so search results, history results, and navigator results (not bookmark, not search input, not settings).

<ctrl-c> and <cmd-c> should continue working as normal in search input (if it doesn't properly copy the highlighted search input, then fix that -- I think for some reason ctrl-c was set to navigator shortcut though it should be ctrl+enter to go to nav).

**Comment by Harjot1Singh** [comment]
Ctrl + c -> g interferes with the g hotkey. how should this work? Would we prefer sequences to take control, and timeout?

**Comment by Harjot1Singh** [comment]
For now, I'm using:

```
cmd+g = copy gurmukhi
cmd+t = copy transliteration
cmd+e = copy english translation
cmd+a = copy author
```
since there's some bug with react-hotkeys with sequenced hotkeys :(

**Comment by bhajneet** [comment]
> Ctrl + c -> g interferes with the g hotkey. how should this work? Would we prefer sequences to take control, and timeout?

A sequence initializer can pause other hotkeys or more obviously a context menu should negate normal hotkeys. Control plus C would open the context menu. Esc would close the context menu. The letter g would activate the gurmukhi context menu.

> since there's some bug with react-hotkeys with sequenced hotkeys :(

Can you work around the bug or is this out of your hands? The four hotkeys you've mentioned will work for now, I was hoping to make the navigator letter g, but we can delay that until this bug is fixed.

**Comment by Harjot1Singh** [comment]
For now, I'm using `ctrl-g` etc. 

I'll have to look into the library itself, because the guy hasn't been around to maintain it for a bit.
