### ISSUE TITLE
Visual autoselect - Replace number hotkey with icons indicating main line and jump line in navigator

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#189]
Use the hotkeys as the replacement. Ideally, this should change if the user puts in custom hotkey, but for now we can use < for main line and > for jump to line/secondary line (this should only be set when using spacebar from a non-main line)

See #103 for related info

**Comment by Harjot1Singh** [comment]
What does use the hotkeys as replacement mean?

**Comment by bhajneet** [comment]
As you can see in hotkeys issue 103 the `S-,` or the `<` key is a hotkey for always returning to the main line no matter what line the user is on and it will not affect the stored main line or the stored secondary/jump-to line. Same thing with `>` hotkey. So we can show these two symbols instead of the number in navigation to the left of the gurmukhi. If 3 line is main, then change 3 to `<`.
