### ISSUE TITLE
Settings button doesn't look for existing settings window

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#194]
Do we want users to be opening multiple settings windows or not?

**Comment by Harjot1Singh** [comment]
If we do, https://stackoverflow.com/a/11344328/6621182

I reckon it should probably only be 1 window though, unless you think others will find it useful.

**Comment by bhajneet** [comment]
Should be one settings window

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
