### ISSUE TITLE
Add VSCode plugin recommendations

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#196]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/.vscode/extensions.json

**Comment by saihaj** [comment]
We can modify `.gitignore` so that we we only exclude`.vscode/extensions.json` instead of removing `.vscode` from that because one can have different `.vscode/settings.json` and we don’t really need those because there can be conflicting commits
