### ISSUE TITLE
Extra pronunciation (transliteration) sources

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#198]
Hindi and Urdu/Shahmukhi are present in the DB. Needs an option in settings > layout (settings > display according to #271) to add to the presenter and also to be added to the overlay.

- [x] Hindi requires Noto Sans Devanagri (Medium, Semibold, Bold choice requires testing against punjabi translit, stroke thickness should be same/similar)
- [x] Urdu/Shahmukhi requires Noto Sans Nastaliq Urdu Regular

Related: #186 #159 #85 #158

**Comment by bhajneet** [comment]
Urdu requires CSS `text-align: right;`

Can go before this declaration https://github.com/ShabadOS/desktop/blob/dev/app/frontend/src/Presenter/Line.css#L12

**Comment by Sarabveer** [comment]
Yea Urdu is Right to Left

**Comment by bhajneet** [comment]
Also related to  #271 this moves it to settings > display

**Comment by Harjot1Singh** [comment]
> text-align: right;

Why does it require this? I'll push it and you can mess about, I can't actually tell if ltr or rtl is automatically set

**Comment by Harjot1Singh** [comment]
Semi bold seems ok. And the font/using unicode already seems to set RTL.
