### ISSUE TITLE
Kobo, Kindle, eReader, tablet endpoint/webpage

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#199]
eReader devices have modified web browsers, whereas tablets (like an iPad) have full-fledged mobile browsers.

Goal is to create a view that allows a singer to see/scroll the entire shabad in gurmukhi. Optionally it would be great to include font-size adjustment, but not as a slider, instead as a number with plus and minus for ease of use.

Settings should allow users to pick different "themes" similar to overlay. Related #197.

**Comment by saihaj** [comment]
mobile app can solve this issue

**Comment by bhajneet** [comment]
Also related to #416
