### ISSUE TITLE
feat(frontend/settings): add presenter & overlay option to dynamically remove metadata from english translations

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#204]
Related #197, could be theme based instead of settings option.

**Comment by bhajneet** [comment]
Because we can learn the numbers from the Gurbani in the transliteration, I would suggest we remove the numbers completely from the translation. This would help us at BoS because we remove them in our edits and so that'd save us time, but I'd also think this would give a much cleaner look in a broadcast.

Thank you

_Originally posted by @preetcharan in https://github.com/ShabadOS/desktop/issues/409_

**Comment by bhajneet** [comment]
Settings > Display > Hide "Metadata" in "Translation and Transliterations"/"Secondary Lines"

Same in Settings > Overlay

**Comment by Harjot1Singh** [comment]
Sources need to be split into global section and these options would apply universally global

**Comment by bhajneet** [comment]
Duplicate of #508
