### ISSUE TITLE
show more info on each search result

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#225]
if we are to include translation/transliteration searches in the future, it would be nice to expose these on the results so they can be highlighted properly.

in the case of transliteration it would be best to highlight both the gurmukhi as well as the translit line.

proposed:

* RAAG AUTHOR SOURCE PAGE:LINE
* MATCH RESULT (depending on search type):
  * GURMUKHI 
  * GURMUKHI + ENGLISH TRANSLATION
  * GURMUKHI + ENGLISH TRANSLIT

**Comment by bhajneet** [comment]
Add option in settings to hide this "metadata"

**Comment by bhajneet** [comment]
Can have a new tab in Settings for "Search"

Options can include:

- Show Metadata (Raag, Author, Source, Page:Line)
- Show English Translation
- Show {English, Hindi, Urdu} Translit (results need to highlight these for gurmukhi searches)

And a tutorial button (which requires a tutorial to be written first)

**Comment by bhajneet** [comment]
Depends on #323 for readability

**Comment by preetcharan** [comment]
Would like to have it in the same format as BoS author rules, if possible to have this in the settings like it is in my customised version

Author - Source - Ang

<img width="411" alt="image" src="https://user-images.githubusercontent.com/41019240/75159350-dea98900-570f-11ea-91dc-1e9fc7870ad6.png">

glad it's going in as a setting as i don't think this is useful to the majority of users

**Comment by bhajneet** [comment]
![mobile mock - 03 - search results](https://user-images.githubusercontent.com/14130567/75483051-fb45fb00-5973-11ea-92c0-4fda05f37125.png)

Can maybe put them on top like this but use the fields requested

**Comment by saihaj** [comment]
> Translation or Tranlist is something users can do in settings &gt; search
![image](https://user-images.githubusercontent.com/44710980/81485212-08ebec80-9211-11ea-9e7e-879886833f61.png)
![image](https://user-images.githubusercontent.com/44710980/81485216-0c7f7380-9211-11ea-86c0-e85ac8983e7a.png)
<sub>[View in Slack](https://shabados.slack.com/archives/CD9QC0XKR/p1589059202060900)</sub>

**Comment by bhajneet** [comment]
I'm not sure what percentage of lines have a section assigned. I also don't know if the sections are easily related to their source for endusers. So for ease right now, let's replace section with source. Let's re-arrange to:

> Author, Source, Page

This may require fixing many of our sources and authors lists since there is bound to be overlap.

**Comment by Harjot1Singh** [comment]
Every line must have a section afaik, since every Shabad belongs to a section. Maybe I’m Wrong though, but this is how I remember the schema.
