### ISSUE TITLE
Fix ctrl+f hotkey or allow F11 hotkey

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#228]
Currently there is no way to "Toggle Full Screen (F11)" without using the menu bar item. The ctrl+f hotkey is opening the built in navigator.

![image](https://user-images.githubusercontent.com/14130567/67611172-ce839c00-f765-11e9-8e7d-885798a90723.png)

Neither of these seem to work:
![image](https://user-images.githubusercontent.com/14130567/67611802-e14c9f80-f76a-11e9-88a5-30bd743ced95.png)

**Comment by Harjot1Singh** [comment]
Unable to reproduce... Maybe related to #219?
