### ISSUE TITLE
Splash screen on load

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#242]
Two instances when this is very helpful:

- After installer is complete, there is at least 15-30 seconds (depending on laptop) before the window appears. This is too long and can make users think that the installer has simply installed and will not run the program automatically. For my relatively-higher end laptop, it took 27 seconds after installer disappeared until the Shabad OS window first showed up.
- During normal start ups (see #241) it would be nice to see some animation immediately to let the user know that something is happening

Can use the animation from social media with some extra words or a simple "loading..." text

**Comment by bhajneet** [comment]
Does not have to be fancy for now. Any simple loader with the words Shabad OS, Loading, and an animation are good enough.

**Comment by bhajneet** [comment]
Should be seen almost instantly to signify something is happening when user launches desktop app

**Comment by Harjot1Singh** [comment]
Can you put together a HTML/CSS visual of what we’d see? Codesandbox it

**Comment by bhajneet** [comment]
https://codesandbox.io/s/boring-yonath-gzlyz?fontsize=14&hidenavigation=1&theme=dark

Random CSS used, but the end result looks about what I think
