### ISSUE TITLE
frontend: default hidden controller requires two activations to open

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#243]
This button requires two clicks to open on startup. If you minimize after that, then it only takes one click (as it should). 

Same with hotkeys. On start up, it takes two commands of "ctrl+h" to unhide it. After that, it's just the one time.

![image](https://user-images.githubusercontent.com/14130567/67639785-731eee80-f8ca-11e9-8edb-5d34d7e8baa7.png)

**Comment by Harjot1Singh** [comment]
Can't seem to reproduce anymore
