### ISSUE TITLE
Unicode search support

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#25]
While using my iOS Gurbani keyboard, I was unable to search.

I suspect this is down to the lack of support for the Gurmukhi/Punjabi unicode characters, and will probably be a useful thing to fix.

**Comment by bhajneet** [comment]
Perhaps for those on english keyboards, we could hotkey to the unicode characters? That way we can keep our "#" character for searching full words and other modifiers in the future.

Main gripe with unicode was fonts subjectively didn't look nice. Perhaps that's changed, I'll look into that again. This reminds me that sometimes people want to copy the shabad, so we could also add a "copy shabad" button in the controller.

**Comment by Harjot1Singh** [comment]
Yeah, I think for English letters should continue to map to the correct Gurmukhi characters as they do now.

Copy is a good shout.

I haven't really looked into other fonts, but might have a quick glance for unicode alternatives

**Comment by bhajneet** [comment]
For dev, we've decided on ascii gurbani, unicode everything else. So now we have to go a bit in reverse and either map unicode to ascii in search (so people's unicode keyboards work on mobile) or keep the ascii to unicode conversion and convert sql query to ascii

**Comment by bhajneet** [comment]
@Harjot1Singh Be sure to double check if this is "done" after switching db

**Comment by Harjot1Singh** [comment]
Fixed in dev. Kept the search box as Unicode input in case someone wanted to copy the input.
