### ISSUE TITLE
add option to opt-out of any auto-updates (app, db, etc.)

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#255]
During critical important events like a smaagam, there may be limited bandwidth and even if there is enough bandwidth a new update could break their current set up in a time when they're not prepared to fix/adjust.

Since there is no easy way to downgrade (and even if there were, you'd still require) a way to stop auto-updates would be very helpful.

**Comment by Harjot1Singh** [comment]
Closed in 660810e
