### ISSUE TITLE
show more search results

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#257]
the "max_results" constants are not working. you can limit below 50-ish, but you cannot add more results by increasing this number. 

searching `kkkk` does not show a result for the line searched by `kkkknsA`

**Comment by Harjot1Singh** [comment]
I've bumped it to 50, but `kkkknsA` doesn't appear still for that.

**Comment by Harjot1Singh** [comment]
Fixed in 22e64e4d352ca23bfb37801cf7d771d64b2a8167
