### ISSUE TITLE
Fix error on failed update

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#276]
![image](https://user-images.githubusercontent.com/14130567/68298861-718ebc80-0068-11ea-9faf-e5ba44c67077.png)

There is no `.exe` in beta 2 release (circle ci randomly failed). So I'm guessing it's trying to find a file that isn't there.

**Comment by Harjot1Singh** [comment]
It's actually looking for `latest.yml` since the release is present, but since the Windows publish randomly failed, so does this.

Solutions:
1) Catch all uncaught exceptions and send to sentry + log it
2) Automatically retry failed publish jobs

**Comment by Harjot1Singh** [comment]
2) isn't possible right now with CircleCI
