### ISSUE TITLE
possible to remove option to translate website?

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#283]
perhaps this can not be helped but chrome often asks to convert the gurmukhi from polish or whatever language it detects it as into english. if there is a way to remove this pop-up it would help the user experience.

**Comment by Harjot1Singh** [comment]
Check if still the case in 2.1.0-*

**Comment by Harjot1Singh** [comment]
Actually, https://support.google.com/webmasters/answer/79812
