### ISSUE TITLE
Name of process should start with "Shabad OS"

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#293]
![image](https://user-images.githubusercontent.com/14130567/68545696-6fe13380-039d-11ea-948f-c54a536e7e89.png)

This is not something I would search for if sorting by name in task manager / process mgr

Can be Shabad OS or Shabad OS Updater or whatever, but should start with Shabad OS at least

**Comment by AkalUstat** [comment]
Task managar here is showing Shabad OS

**Comment by Harjot1Singh** [comment]
I know how to consolidate the two - change the description in app/package.json to Shabad OS I believe
