### ISSUE TITLE
Allow search hotkey from search activity

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#319]
When already searching, one cannot use ctrl+/ key to activate search again. This should allow user to highlight search query string for a new search.

**Comment by Harjot1Singh** [comment]
Given #318 and #223, is this still relevant? Not sure I understand the functionality entirely. Ctrl + / for highlighting the query in the same way as #318?

**Comment by bhajneet** [comment]
Ctrl+/ from the search activity should highlight the entire query as it
would if going to the search activity from another activity like
history/bookmarks

Currently doesn't seem to do that

If I've gone down a few results and want to search something with hotkey it
doesn't focus the search bar for a new query, in this case a new line is
being sung and want to search that instead

**Comment by bhajneet** [comment]
We could also have this swap the input mode. Or long-press can swap input mode.

**Comment by bhajneet** [comment]
Ctrl+a is an acceptable alternative
