### ISSUE TITLE
Fix pino critical crashing error

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#320]
Make pino run in it's own thread https://www.npmjs.com/package/pino

If possible, also investigate why pino crashes.

**Comment by Harjot1Singh** [comment]
Can't use the functional programming style with `pino`, see https://github.com/pinojs/pino/issues/569

**Comment by Harjot1Singh** [comment]
This bug was introduced in `alpha.13` https://github.com/ShabadOS/desktop/commit/da450652db48da7ce522eb1f558d50834ed0b8cc
