### ISSUE TITLE
EACCESS denied to history/themes/etc

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#324]
EACESS denied to history, the history file is unable to get written, so after the first search, it crashes since it can’t write this

If you try this for now -> delete /Users/YOUR ACCOUNT/Library/Application Support/Shabad OS/history and run Shabad OS again it will temporarily fix the issue

Suspect the solution is to delete the folder automatically if there’s a perm issue or similar

**Comment by Harjot1Singh** [comment]
Closed in 647efc1ca5b166ccb275ea85722c46d836ad4317
