### ISSUE TITLE
Test double tap issue on iOS devices

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#326]
User report:

> One other thing - when you select a line on the phone I had to press twice sometimes. To me it seemed like it was highlighting the line first time (didn’t change the screen still) but then when pressed firmly again it would then change.  Not sure if others have had this experience...
> 
> Say your on a shabad and then want to select a line. What I’m finding is that it highlights it but it doesn’t actually firmly change the slide. You then have to take your thumb off and then select it once again and it then recognised it and transitions to the next slide
>
> I’m using iphone x

**Comment by bhajneet** [comment]
On hold until performance improvements are implemented in frontend

**Comment by bhajneet** [comment]
@Harjot1Singh were you able to reproduce this before the commit?

**Comment by Harjot1Singh** [comment]
Yes, noted that the tap would stop working after 3s delay
