### ISSUE TITLE
updated to beta even though option is toggled off

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#328]
![image](https://user-images.githubusercontent.com/14130567/70161953-e31f5200-168a-11ea-9483-6526eb244921.png)

After closing it showed the installer, then on settings > about: 

![image](https://user-images.githubusercontent.com/14130567/70162014-fcc09980-168a-11ea-8985-a6ba5ee317a8.png)

**Comment by Sarabveer** [comment]
Experienced same issue

**Comment by Harjot1Singh** [comment]
We should review when the next beta release is released, it's simply a CI config error over a desktop logic issue
