### ISSUE TITLE
Timestamp format doesn't match OS

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#341]
07:28 PM =/= 19:30

Also the PM doesn't fit in this space on one line. I don't think we even need AM/PM it should be kind of self-evident, very few programs repeat the same hour twice. Regardless, if we keep AM/PM, the hour should not have a leading 0

![image](https://user-images.githubusercontent.com/14130567/71300020-5699b280-235f-11ea-9842-40a8ac6affdc.png)

**Comment by Harjot1Singh** [comment]
Ah. This is from `.toLocaleTime()`, which uses the browser's preferred format string afaik

**Comment by bhajneet** [comment]
Perhaps related to https://github.com/electron/electron/issues/13023 ?

If so, we can add "on hold" tag and keep either 24 hour or 12 hour without AM/PM and leading zero for now as the resolution.

**Comment by Harjot1Singh** [comment]
We could, but I’d bump it fairly low, priority-wise, it’ll take longer than it’s worth at this point.

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
