### ISSUE TITLE
Compare updates instead of installing blindly

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#356]
Even if the beta and stable are the exact same the app will update from beta to stable of the same version. It should not be installing anything but updating it's own internal version number if this happens. Need a comparison method like md5 hash or such.

**Comment by Harjot1Singh** [comment]
How does the user end up in the situation?

**Comment by bhajneet** [comment]
They end up downloading a new update unnecessarily, possibly costing time and bandwidth depending on method. I marked it low, because I doubt this will happen often (ever?) where we have no changes between the beta of a release and it's stable release.

**Comment by Harjot1Singh** [comment]
I don't think it'll ever be possible, since a version bump in `package.json` will constitute a hash change 🤔

**Comment by bhajneet** [comment]
Okay no worries, closing
