### ISSUE TITLE
Larrivaar applies to more than gurbani

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#363]
Either rename the setting from Larrivaar Gurbani to simply "Larrivaar" or change the behavior of presenter/overlay to match the toggle (and display gurbani only in larrivaar)

![image](https://user-images.githubusercontent.com/14130567/72293398-71d7a500-3621-11ea-96c8-2c32a16c0246.png)

The first makes sense, if transliteration is actually 2-ways (it's not, but we can strive towards that). If there is ever a "pronunciation" field as opposed to a transliteration field, then I don't see why it should be larrivaar as well.

**Comment by Harjot1Singh** [comment]
I would still say that translit/pronunciation should be in Larivaar too, since the way the words are joined up can affect the pronunciation (so it’s more subjective in Larivaar)

**Comment by bhajneet** [comment]
Then rename it to Larrivaar Paath maybe?
