### ISSUE TITLE
"Settings > About" should show OS instead of Platform

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#365]
Better than knowing whether it's Windows, macOS, or Linux it would help to know specifically which version of Windows, macOS, or Linux is being used.
![image](https://user-images.githubusercontent.com/14130567/72293758-2bcf1100-3622-11ea-8298-a55b14037afa.png)

**Comment by visionthroughdesign** [comment]
Are we able to use `require('os').release() ` to achieve this?

**Comment by Harjot1Singh** [comment]
Very possibly, i think we're currently using `.platform()`
