### ISSUE TITLE
Add info button for line/shabad

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#378]
I don't think this box is used for anything really:

![image](https://user-images.githubusercontent.com/14130567/72446356-6c916c00-3781-11ea-831f-c0a7a5970a84.png)

Perhaps we can replace it with an info button that includes writer, source, permalinks for shabad and line, as well as a link to our db-viewer for corrections.

**Comment by bhajneet** [comment]
Note this has to be tested on mobile devices to make sure it doesn't break layout

**Comment by Harjot1Singh** [comment]
I was so-so on this before, but to be honest, i think an info button will add more value.

DId we have an issue though for quick-scrolling to sections?

**Comment by bhajneet** [comment]
I don't believe we do. We can close it later if we find it.

Do the arrows bring any value either? Perhaps we should get rid of those as well. It was originally for lazy clicking / tapping on mobile to next line. But given it's small size on mobile and hiding controller to click through lines, I don't think the arrows serve any purpose either.

In which case I would propose the new bottom bar to be:

- Search, History, Bookmarks, Navigator on left side (activities)
- Info and autoselect on the right side (activity specific buttons)

Not sure where "esc/alt" screen button should go. It's not an activity and it doesn't pertain to any one specific activity (or arguably pertains to all of them? so could be the far right most icon, which it already is).

**Comment by bhajneet** [comment]
Also helpful to allow copying of the entire shabad instead of individual lines like #188

**Comment by Harjot1Singh** [comment]
- Link to DB viewer to correct
- Use popover etc
- Copy shabad etc

- Raag, Author, Source, Page

**Comment by saihaj** [comment]
Where should the `i` be?
![image](https://user-images.githubusercontent.com/44710980/78822932-7eaa3180-79a1-11ea-8444-b42556088426.png)

**Comment by bhajneet** [comment]
Correctly placed in your image
