### ISSUE TITLE
Buttons don't match (settings > overlay)

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#379]
![image](https://user-images.githubusercontent.com/14130567/72448588-42da4400-3785-11ea-9338-1597a9d189c7.png)

**Comment by Harjot1Singh** [comment]
Which do you prefer?

**Comment by bhajneet** [comment]
- use top button
- rename "View Livestream Tutorials" to "Learn how to use overlays" move to absolute top (first item)
- move "Open Overlay Folder" to between overlay name and larivaar gurbani

End order: view tutorial button > overlay url copier > overlay name dropdown > open overlay folder button > display toggles

**Comment by bhajneet** [comment]
Similar to this:
![image](https://user-images.githubusercontent.com/14130567/72546363-aa14f880-3858-11ea-9c6e-c8e2ec6706d3.png)
