### ISSUE TITLE
npm run pack/dist results in "Cannot Get /"

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#380]
pack is much faster than dist to test out production builds

**Comment by bhajneet** [comment]
Actually this is occuring with dist now as well...

**Comment by Harjot1Singh** [comment]
You need to build frontend too if you’re building local prod:

`npm run build && npm run pack`

**Comment by bhajneet** [comment]
Do you always run build before pack/dist? If so, package.json can be updated with commands that include build

**Comment by Harjot1Singh** [comment]
not always, only if i know the frontend has changed. but that happens a lot, so maybe i can, but it adds 1-2 mins to the command

**Comment by bhajneet** [comment]
Closing as user error
