### ISSUE TITLE
Random failure to update colors / theme for material ui

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#382]
Have noticed this a couple times on refresh as well:

![image](https://user-images.githubusercontent.com/14130567/72544224-f0685880-3854-11ea-8b0a-bb78387f2ae6.png)

**Comment by Harjot1Singh** [comment]
Easy way to reproduce: remote control settings from another device. Colours go wrong. I suspect it's a `defaultValue`/uncontrolled component issue
