### ISSUE TITLE
Add english transliteration first letters search

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#393]
Depends on https://github.com/ShabadOS/gurmukhi-utils/issues/105 (Add firstLetter for English Transliteration)

Add toggle to convert ascii to gurmukhi or not in the search bar (left side).

Not sure how we will handle double-char first letters. Might have to require "space" in between each letter to parse.

**Comment by bhajneet** [comment]
Not to mention alternative transliterations

**Comment by Harjot1Singh** [comment]
Duplicate #397.
