### ISSUE TITLE
Don't advance line when clicking "+" sign to open controller

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#401]

**Comment by bhajneet** [comment]
On an iPad with a hidden controller, users accidentally advance the line just to open or view the + sign to click on.

With no way to easily go back a line, this can lead to the wrong line being displayed for a long period of time.

**Comment by bhajneet** [comment]
Related #352 which would help on iOS to retreat a line.

**Comment by saihaj** [comment]
#451 closes this

**Comment by saihaj** [comment]
#451 was not merged

**Comment by bhajneet** [comment]
This was archived / removed from Proj Mgmt.
