### ISSUE TITLE
Application disappears on Full Screen toggle or Desktop Swipe

### ISSUE THREAD

**Issue by visionthroughdesign** [ShabadOS/desktop#412]
ShabadOS Version: 2.3.1
OS: 10.14.6 (18G2022)

Scenario: 

1) If you click on the fullscreen toggle for ShabadOS, the application disappears. 
2) If you swipe desktops to another screen and return back to the original, the application is no longer visible. 
3) If you pop out controller, full screen controller and swipe back to the initial ShabadOS screen, the application is no longer visible 

Result: ShabadOS is completely unavailable/inaccessible, to bring the application back you have to exit out and reopen app.

**Comment by bhajneet** [comment]
Could this help? https://github.com/ShabadOS/desktop/commit/066fe2ce5e1e0671f5fdff1fba4b1b93341ee5fe

Build available on Circle CI. To test Shabad OS hotkey vs macOS titlebar buttons.

**Comment by Harjot1Singh** [comment]
Can we figure out which version introduced this? I'll try to bisect it.

**Comment by Harjot1Singh** [comment]
```
[22:20:50.464] ERROR: Object has been destroyed
    Error: Object has been destroyed
        at BrowserWindow.<anonymous> (/Users/harjot/Projects/ShabadOS-desktop/app/electron/electron-wrapper.js:36:50)
        at BrowserWindow.emit (events.js:208:15)
        at BrowserWindow.EventEmitter.emit (domain.js:476:20)
        at BrowserWindow.topLevelDomainCallback (domain.js:131:23)
```
on switching back to the desktop of Shabad OS, after switching away.

**Comment by Harjot1Singh** [comment]
Any thoughts or pointers to documentation on why this happens? Basically, when you show the window on Mac, after it's been minimised or from another desktop, it calls the .on('show') handler each time... on Windows it does not do this.

The crash is caused by the handler trying to destroy the splashscreen, even though it's already gone lol
