### ISSUE TITLE
Add reset buttons to some settings tabs

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#418]
Namely display and layout.

Could there also be "reset to factory defaults" kind of button in "system options" which return shabad os to it's original installation? Basically resetting everything to defaults.

**Comment by Harjot1Singh** [comment]
First task is easy.

2nd task, there’s a difference between default installation and default settings, so we need to be clear on which one we’d like

**Comment by bhajneet** [comment]
What's the difference between default installation and default settings?

**Comment by Harjot1Singh** [comment]
Default installation suggests the same database at time of install etc, and removal of all additional artifacts (history, Logs, etc)

**Comment by bhajneet** [comment]
No we don't need that

Reset to default settings is fine. It will reset the frontend.
