### ISSUE TITLE
Change Ctrl+Spacebar Hotkey

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#42]
This is too close to doing the combo Left+Spacebar (When on a second line of rahao and trying to select mainline to autoselect the next line). Ctrl+Shift+Spacebar is fine, it's not an often used hotkey and should still be easy enough to do one-handed on most laptops.

**Comment by Harjot1Singh** [comment]
What is this? Are you able to open an issue with a list of the required hotkeys?

**Comment by bhajneet** [comment]
Shifted to #103
