### ISSUE TITLE
Fix next/prev lines covering each other when wrapped

### ISSUE THREAD

**Issue by AkalUstat** [ShabadOS/desktop#420]
![AF6D7F09-5545-4B66-A3F9-CC368ADA9A73](https://user-images.githubusercontent.com/43657841/74679590-24e07480-5173-11ea-9266-cf1ea30c13c6.jpeg)

**Comment by bhajneet** [comment]
Windows 10, Firefox:
![image](https://user-images.githubusercontent.com/14130567/74688662-38f19980-51a6-11ea-8dcf-8141de6db5f2.png)

Have to somehow investigate the built-in iOS WebKit-based rendering framework.
