### ISSUE TITLE
Add a comma for combo hotkeys

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#424]
![image](https://user-images.githubusercontent.com/14130567/75039735-49945f00-5487-11ea-8e1c-d88e38f3e7e4.png)

i.e. `ctrl+c, g`

**Comment by Harjot1Singh** [comment]
![image](https://user-images.githubusercontent.com/1184274/75059825-a585d480-54d5-11ea-92b4-9aa4761f045b.png)
I'm finding the comma a little confusing

**Comment by bhajneet** [comment]
Either way may be confusing for the user. Let's leave without comma for now. If there are more advanced combos we can re-visit, but we probably don't want to key stroke that far. It will be easier when ctrl+c shows a context menu and G, T, H, etc. keys are underlined for the menu items.
