### ISSUE TITLE
Add hotkey for copying gurmukhi in unicode

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#427]
![image](https://user-images.githubusercontent.com/14130567/75040039-ece57400-5487-11ea-8250-f36c4d512718.png)

Add "Copy Gurmukhi (Unicode)"

**Comment by Harjot1Singh** [comment]
What the hotkey?

**Comment by bhajneet** [comment]
g vs G (shift key)

Which should be which? I'm guessing more people want unicode for simplicity even though it might be inaccurate in a few cases. So I would say lower g for that and shift g for ASCII. But can swap around, as long as both are available and easy to see in hotkeys menu, all good. User can change too when we have customizability.
