### ISSUE TITLE
Allow custom characters for vishraams

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#43]
Puneet Singh mentioned that it would be nice to use spacing to differentiate vishraams. Though he understands that vishraams using spaces at the end of a line-break is difficult to figure out, it is still something he'd like to be able to do. Allowing custom characters would let him put say 4 spaces for heavy vishraams.

**Comment by Harjot1Singh** [comment]
Is this a visual issue? 4 spaces to separate on screen?

**Comment by bhajneet** [comment]
It's just customizability, some people might not want colors or commas to signify pauses. They might want to use differing lengths of spaces to signify the weight of pauses

**Comment by Harjot1Singh** [comment]
I see - also looking through the database, I think that we should be using non-visual characters to signify these things, and then color/do whatever, so that others can use the database without any extra post-processing.

**Comment by bhajneet** [comment]
That's an option, but with an API it should also not be much work for the end-user. We could use a column to signify the positions of the pause as another option so it's more transparent.

**Comment by Harjot1Singh** [comment]
I did think about this, but it basically means maintaining a separate table since there are many positions per each line, and it's a pain to update if someone makes a change to the line. I wonder if there's a better way than recording the positions?

**Comment by Harjot1Singh** [comment]
Ah, I understand what you mean now. It seems reasonable to be able to pass in a config parameter to our API to strip out the characters if need be.

**Comment by Harjot1Singh** [comment]
Presumably this would be a toggle?

**Comment by bhajneet** [comment]
It could just be an input box with a reset button too

**Comment by bhajneet** [comment]
I do not believe this is helpful to enough users
