### ISSUE TITLE
Use matching button styles in settings

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#432]
![image](https://user-images.githubusercontent.com/14130567/75069719-c9d6b680-54bf-11ea-8a27-7a1b051f8a46.png)

**Comment by saihaj** [comment]
Can you tell more about what you mean by "matching button styles"?

**Comment by bhajneet** [comment]
There seems to be 2 "styles" of buttons in settings right now.

One style is gray background ("Reset to Defaults" in all the tabs)

And the other style is white background ("Learn More" and "Open Overlay Folder" in the Overlay settings).

I would like all the buttons to be of one style. Preferably the white background for the day theme. You'll have to check the other themes to see what works best too. Could be a simple case organizing/redoing a little of the CSS.
