### ISSUE TITLE
Copy doesn't work on first hotkey stroke

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#437]
It felt as though the copy function wasn't working the first time every once in a while. Reported by two users.

**Comment by preetcharan** [comment]
only works on second stroke for me on mac ver 2.5.0

**Comment by bhajneet** [comment]
Confirmed first hotkey stroke shows "copied" pop-up, but pasting elsewhere does not concur

**Comment by bhajneet** [comment]
Confirmed *not working* on 176-customizable-hotkeys.

Reproduce:

1. Start new instance of Shabad OS
2. Search a shabad and open it in navigator
3. Use copy hotkey sequence
4. Notice the pop up that says it's copied
5. Try to paste, but does not show what was supposedly copied

**Comment by saihaj** [comment]
@Harjot1Singh how can I get started?

**Comment by Harjot1Singh** [comment]
> @Harjot1Singh how can I get started?

You're going to want to check if the handler is just not being fired the first time at all to start with. If it's not, find out why. It could be a race-condition or render issue. Test to see if it's any better when you supply a hardcoded keymap and handlers. There are a couple of components which handle different hotkeys, but copy hotkeys are handled in `CopyHotkeys.js`

**Comment by saihaj** [comment]
In browser, this is not an issue. So this has to do something with Electron.

**Comment by saihaj** [comment]
@Harjot1Singh what should I do. Because if it was a render issue then it should exist in browser too (Or my assumption is wrong?)

**Comment by Harjot1Singh** [comment]
Do some console logging to confirm whether the handler is firing or not.

**Comment by bhajneet** [comment]
I have noticed that in production release if you change shabads it again fails to register the first copy hotkey.

**Comment by saihaj** [comment]
> Do some console logging to confirm whether the handler is firing or not.

I modified this reducer [`shared/CopyHotkeys.js`](https://github.com/ShabadOS/desktop/blob/fc01ec563178ad605e42c2274b030da366063a13/app/frontend/src/shared/CopyHotkeys.js#L49-L69) to log. So it is returning the line that I am currently at and that is expected. But the state of `useCopyToClipboard` hook is not updating. Something wrong with the hook? 

```
...

].reduce( ( hotkeys, [ name, getContent, fieldName ] ) => ( {
    ...hotkeys,
    [ name ]: () => {
      console.log( getContent() )
      copyToClipboard( line && getContent(), `No ${fieldName} available to copy` )
    },
  } ), {} )

...

```

**Comment by saihaj** [comment]
> Something wrong with the hook?

So I logged the hook to see what is being passed to it and correct text is being passed down. Now it is all on [copy-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard) that handles copying.

**Comment by saihaj** [comment]
> I have noticed that in production release if you change shabads it again fails to register the first copy hotkey.

Does not work on dev

**Comment by saihaj** [comment]
#573 will temporarily fix this but an ideal solution is resolution of sudodoki/copy-to-clipboard#90
