### ISSUE TITLE
Add plugin/side-app to query Shabad OS API for copying in BoS formats

### ISSUE THREAD

**Issue by preetcharan** [ShabadOS/desktop#438]
When copying author, would like to change format of the following things to:

-Sri Guru Granth Sahib Ji to 'SGGS Ji' 
-For dasam bani, Remove panna from Sri Dasam Granth as it's not accurate as far as i'm aware, so just Guru Gobind Singh Ji - Sri Dasam Granth
-same with Bhai Gurdas Ji, change to 'Bhai Gurdas Ji - Vaaran'
-Guru Amardas Ji to Guru Amar Das Ji
-Guru Raamdas Ji to Guru Raam Das Ji

**Comment by Harjot1Singh** [comment]
@bhajneet not sure how to approach this - we use the default source names and author names as defined by the database. Is there an extensible solution to this? Or should we look at developing a plugin/side-app to support BoS?

**Comment by bhajneet** [comment]
I think a plugin/side-app must be used for this level of customization. I can't imagine this level of specificity being used by 80% of our users.

Could have something that "queries the API" when running Shabad OS and converts them to whatever BoS needs.

This way we can also have proper MLA/APA citations for reference/scholarly work and a separate citation method for BoS. _Related to #429_. Our sources are supposed to be based on "publications" so we'd change it to something like 

`Bhai Nand Lal Granthavali. Edited by Ganda Singh, 4th ed., Punjabi University, Patiala, 2009, p. 143, www.sikhbookclub.com/Book/Bhai-Nand-Lal-Granthavali. Accessed 22 Jan 2019.`

As we proof, the better the citations will become.

**Comment by bhajneet** [comment]
It would make more sense if BoS or Preetcharan opened up a repo for this than for us to host such a specific app. Can maybe work on licenses to make it so that if we want to make it more useful to other orgs we can pull it back into this org with a repo honoring the original's license. What do you think @Harjot1Singh ?

**Comment by bhajneet** [comment]
I think this has been resolved with short names being added to db

Even if not, we can hard code requirements for BoS in Shabad OS desktop even if it differs to Shabad OS database as a much easier solution than writing an API and interface
