### ISSUE TITLE
Add ability to refresh Overlay Dropdown

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#448]
Either a refresh button, refresh on opening dropdown, or maybe adding folder watchers to the backend so it's always up to date. Whatever is most likely to not cause issues for end user to find new overlays.

Marked medium since we have an alternate way already.

**Comment by bhajneet** [comment]
Should refresh when the drop down is opened

**Comment by bhajneet** [comment]
@saihaj please commit the work to a draft PR or remove WIP status

**Comment by saihaj** [comment]
@bhajneet is Refresh Button an option?

**Comment by bhajneet** [comment]
That could work for now
