### ISSUE TITLE
Create hotspot option

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#45]
In case there is no wifi available, the program should use the wifi adapter to create it's own hotspot that others can connect to

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.

**Comment by saihaj** [comment]
can be solved once we have connect : )
