### ISSUE TITLE
Translation undefined for jlkrn

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#453]
Jab Lag Khalsa Rehe Niara causes crash. Let's fix. Might be introduced by hooks rewrite.

**Comment by bhajneet** [comment]
How do you recreate? I cannot crash even with all display fields enabled

**Comment by Harjot1Singh** [comment]
Hmm I’ll try again on my laptop, and send over settings. Think #262 needs to be sorted lol

**Comment by Harjot1Singh** [comment]
Resetting the settings actually sorted this
