### ISSUE TITLE
Use new GurbaniNow ASCII fonts

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/desktop#458]
Need to add support for subscript numbers, from https://github.com/ShabadOS/database/pull/1488

**Comment by saihaj** [comment]
what font are we adding?

**Comment by bhajneet** [comment]
https://github.com/GurbaniNow/gurmukhi-fonts/releases 2.5.1

**Comment by saihaj** [comment]
Is there a way for me to check that it changed something or not?
