### ISSUE TITLE
Shabad OS crashes if it cannot ping GitHub release page

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#469]
This needs to be patched ASAP

@saihaj can you take a look?

**Comment by bhajneet** [comment]
`{"level":50,"time":1587483787890,"pid":19864,"hostname":"windowslaptop","msg":"net::ERR_HTTP_RESPONSE_CODE_FAILURE","stack":"Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE","type":"Error","v":1}`

**Comment by bhajneet** [comment]
[2020-05-07_22-08-17.052Z.log](https://github.com/ShabadOS/desktop/files/4596032/2020-05-07_22-08-17.052Z.log)

**Comment by Harjot1Singh** [comment]
Solution: https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-413117520

autoDownload = true causes it to not any exceptions from that procedure except to the main process handler
