### ISSUE TITLE
Fix crash on pressing up/down gui buttons on first/last line

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#476]
![image](https://user-images.githubusercontent.com/14130567/80990694-c25b5400-8e04-11ea-8c93-30423e83f2c9.png)

When it reloads (automatically on countdown expiration or manually by user) it simply opens the shabad as it should.

Cannot reproduce consistently.

Attaching logs when it happens going forward ...

**Comment by bhajneet** [comment]
[2020-05-08_14-43-08.172Z.log](https://github.com/ShabadOS/desktop/files/4599876/2020-05-08_14-43-08.172Z.log)

At the bottom:

>{"level":30,"time":1588951117408,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C disconnected","v":1}
{"level":30,"time":1588951117565,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C connected","v":1}

**Comment by bhajneet** [comment]
Crashed again going from these two lines, then to next "shabad"

>{"level":30,"time":1588951170080,"pid":4484,"hostname":"BSK-X1C","msg":"Checking for database updates satisfying @shabados/database@^4.7.0","v":1}
{"level":30,"time":1588951177343,"pid":4484,"hostname":"BSK-X1C","msg":"Local Database Version: 4.7.0","v":1}
{"level":30,"time":1588951177343,"pid":4484,"hostname":"BSK-X1C","msg":"Remote Database Version: 4.7.0","v":1}
{"level":30,"time":1588951177343,"pid":4484,"hostname":"BSK-X1C","msg":"No database updates available","v":1}
{"level":30,"time":1588951217982,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to V26Z","v":1}
{"level":30,"time":1588951218681,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Shabad ID to 843","v":1}
{"level":30,"time":1588951218681,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to NVNP","v":1}
{"level":30,"time":1588951218682,"pid":4484,"hostname":"BSK-X1C","msg":"Setting mainLineId to NVNP","v":1}
{"level":30,"time":1588951218682,"pid":4484,"hostname":"BSK-X1C","msg":"Setting nextLineId to NVNP","v":1}
{"level":30,"time":1588951230040,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C disconnected","v":1}
{"level":30,"time":1588951230190,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C connected","v":1}

**Comment by bhajneet** [comment]
Went to next shabad, no issue, went back, and tried again -- another crash:

>{"level":30,"time":1588951284852,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to NVNP","v":1}
{"level":30,"time":1588951285589,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Shabad ID to SGB","v":1}
{"level":30,"time":1588951285589,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to 8EEH","v":1}
{"level":30,"time":1588951285590,"pid":4484,"hostname":"BSK-X1C","msg":"Setting mainLineId to 8EEH","v":1}
{"level":30,"time":1588951285590,"pid":4484,"hostname":"BSK-X1C","msg":"Setting nextLineId to 8EEH","v":1}
{"level":30,"time":1588951286673,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Shabad ID to 843","v":1}
{"level":30,"time":1588951286674,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to NVNP","v":1}
{"level":30,"time":1588951286674,"pid":4484,"hostname":"BSK-X1C","msg":"Setting mainLineId to NVNP","v":1}
{"level":30,"time":1588951286675,"pid":4484,"hostname":"BSK-X1C","msg":"Setting nextLineId to NVNP","v":1}
{"level":30,"time":1588951287134,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Shabad ID to CSQ","v":1}
{"level":30,"time":1588951287135,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to V26Z","v":1}
{"level":30,"time":1588951287135,"pid":4484,"hostname":"BSK-X1C","msg":"Setting mainLineId to 2HY4","v":1}
{"level":30,"time":1588951287136,"pid":4484,"hostname":"BSK-X1C","msg":"Setting nextLineId to 2HY4","v":1}
{"level":30,"time":1588951288362,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Shabad ID to 843","v":1}
{"level":30,"time":1588951288362,"pid":4484,"hostname":"BSK-X1C","msg":"Setting Line ID to NVNP","v":1}
{"level":30,"time":1588951288363,"pid":4484,"hostname":"BSK-X1C","msg":"Setting mainLineId to NVNP","v":1}
{"level":30,"time":1588951288363,"pid":4484,"hostname":"BSK-X1C","msg":"Setting nextLineId to NVNP","v":1}
{"level":30,"time":1588951299718,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C disconnected","v":1}
{"level":30,"time":1588951299844,"pid":4484,"hostname":"BSK-X1C","msg":"BSK-X1C connected","v":1}

[2020-05-08_14-43-08.172Z.log](https://github.com/ShabadOS/desktop/files/4599891/2020-05-08_14-43-08.172Z.log)

Restarting Shabad OS now...

**Comment by bhajneet** [comment]
Recreate (one scenario! this happens in others as well, though I don't know how just yet):

- Open Shabad OS 2.6.0
- Restore window (req?)
- Bookmarks > Ardas
- Space (goes to "dasavaan paatishaah sree guroo gobind singh saahib jee ...")
- Search > `dpsggs`
- 🔥 Fake Crash 🔥 
- Wait for timeout
- Shabad loads just fine
- Go to second line (last line) of shabad
- Click "down arrow" gui button for next shabad
- 🔥 Fake Crash 🔥 
- Wait for timeout
- Shabad loads just fine

Attached logs:

[2020-05-08_15-23-21.110Z.log](https://github.com/ShabadOS/desktop/files/4599907/2020-05-08_15-23-21.110Z.log)

**Comment by saihaj** [comment]
This is related to info popover because once we added that this started to happen. Me and @Harjot1Singh tried to fix most of the issue before merging it in but it crashes on first and last lines.

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/desktop/pull/503/files/5a57a08ca5fcc2eb086c94b8c865e875786d5142#diff-077d3cb94c5f8ce4f2a0fb13436a5509L214

_Originally posted by @saihaj in https://github.com/ShabadOS/desktop/pull/503_

**Comment by saihaj** [comment]
Resolution took 15 minutes

**Comment by bhajneet** [comment]
So presumably it should have been tagged "Difficulty: 0" haha
