### ISSUE TITLE
no such table: SHABAD

### ISSUE THREAD

**Issue by SikhNerd** [ShabadOS/desktop#49]
Fateh ji,

Very very cool project. I tried building and running this on my mac but immediately ran into an issue. I tried both the latest release version of the database, as well as building it myself and got the same issue:

```go
--------------------------------------------------------------------------------
Error Code: 11
no such table: SHABAD
--------------------------------------------------------------------------------
2018/05/08 23:14:24 http: panic serving [::1]:59411: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc4202800a0)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1726 +0xd0
panic(0x454ac80, 0x484a710)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
database/sql.(*Stmt).Close(0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10.2/libexec/src/database/sql/sql.go:2493 +0x2e
panic(0x454ac80, 0x484a710)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
database/sql.(*Stmt).QueryContext(0x0, 0x461e800, 0xc4200c2008, 0xc4200759a0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10.2/libexec/src/database/sql/sql.go:2376 +0x4e
database/sql.(*Stmt).Query(0x0, 0xc4200759a0, 0x1, 0x1, 0x1, 0x45c4538, 0x1)
        /usr/local/Cellar/go/1.10.2/libexec/src/database/sql/sql.go:2431 +0x65
main.getResultsHTML(0x461e480, 0xc4202940e0, 0xc420184e00)
        /Users/ms/go/src/shabadOS/main.go:592 +0xf0f
net/http.HandlerFunc.ServeHTTP(0x45e5028, 0x461e480, 0xc4202940e0, 0xc420184e00)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201831a0, 0x461e480, 0xc4202940e0, 0xc420184e00)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2337 +0x130
main.CORS.func1(0x461e480, 0xc4202940e0, 0xc420184e00)
        /Users/ms/go/src/shabadOS/main.go:119 +0x24f
net/http.HandlerFunc.ServeHTTP(0xc42014c620, 0x461e480, 0xc4202940e0, 0xc420184e00)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc4202720d0, 0x461e480, 0xc4202940e0, 0xc420184e00)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4202800a0, 0x461e7c0, 0xc42002e9c0)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2795 +0x27b
```

If I get time I'll dig in, but clearly there is a `SELECT ... FROM SHABAD` [somewhere](https://github.com/ShabadOS/core/blob/834093d900b3fee5f12279a33c06eaec281ed1b9/main.go#L334) pointing to this table which doesn't seem to exist.

Keep up the great work, I look forward to digging in as I get more time, including into this issue if you don't get to it before me.

**Comment by SikhNerd** [comment]
Ah, guess it's looking for a second sqlite db that doesn't exist as far as I can tell, and at a _very_ quick glance don't see how to create.

**Comment by Harjot1Singh** [comment]
WJKK WJKF! 
Glad you like the project :)

Did you use the initial release of the DB? I believe that's the one that needs to be used for a build.
Additionally, I believe @bhajansweet did some Mac builds, but they don't seem to work with everyone.

I've checked out some of your projects - they seem really cool, we've also got an open [Slack ](https://join.slack.com/t/shabados/shared_invite/enQtMzUxNDE1Njc3NDQ2LTdhNWQ2MWNlNmEwY2Y4MTA4OTBjMzJhYmZiZmJkOGZmZTRjZjRiYTZmYmNkNzcyZTg0MmFiMTQ0MWQ1YzNkZGU) which anyone is free to join, and it'd certainly be great to talk further and help you out.

**Comment by bhajneet** [comment]
As harjot has already said, there is one "initial db" you should use for the golang project. The new db's are for our re-written desktop app that is more javascript based.

You can download the 35MB original DB from here: https://drive.google.com/open?id=1X5DeizuIm3OzjxGmYlAnUvj3V_sE0KHZ

It is not SGPC compliant, so it contains some mistakes (mostly in terms of spacing / padched, larivaar should be fine).

Once we have the new core, desktop, and database integrated we'll work on fixing all those mistakes and getting it 100% matched to the SGPC saroops.

I hope this helps resolve your issue and if you're having any more problems, please don't hesitate to ask. I also read through some of your blog, some interesting posts -- hope you can get some of those ideas 
/ problems channeled through here :)
