### ISSUE TITLE
Bottom bar overflow on mobile browsers

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#491]
![Screenshot_20200508-105145](https://user-images.githubusercontent.com/14130567/81418100-2722f100-911a-11ea-92ac-b08f82724bcc.png)

**Comment by saihaj** [comment]
Works well on iPhone 11. But not on iPhone 8. Need to add something for device screen ratio.

**Comment by bhajneet** [comment]
Perhaps we should consider switching to a drawer for desktop as it would also match mobile

**Comment by bhajneet** [comment]
And we can focus on 4-6 icons instead of trying to fit 9

**Comment by saihaj** [comment]
Easy fix will be to scale the icon sizes down.

>Perhaps we should consider switching to a drawer for desktop as it would also match mobile

Probably can try that out

**Comment by bhajneet** [comment]
Scaling them down makes them harder to press

**Comment by bhajneet** [comment]
Remove up and down arrows for mobile

**Comment by bhajneet** [comment]
_Related https://github.com/ShabadOS/desktop/issues/321_

**Comment by saihaj** [comment]
Do we want to show the Info button?
