### ISSUE TITLE
Info panel does not track well with resizing

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#494]
See popped out controller. It got stuck here after maximizing and restoring window size:

![image](https://user-images.githubusercontent.com/14130567/81419114-bc72b500-911b-11ea-9308-7384bd6ab7c1.png)

Can this be fixed?

**Comment by saihaj** [comment]
Does not happen in FireFox and Electron dev mode on Mac.

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
