### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/desktop#499]
As discussed in Slack we should try out the release notes.

**Comment by bhajneet** [comment]
I'll open a PR for 4.6.0 release notes, and then we can start doing them for dev as well

**Comment by bhajneet** [comment]
This will tie into _Release Notes/Changelog #106_

**Comment by Harjot1Singh** [comment]
I don't remember how we decided to deal with assets :/ LFS ended up being a non-starter afaik, pricing

**Comment by bhajneet** [comment]
I believe we only needed LFS to handle repo download size -- If we use a separate docs (current tutorial) repo, it should be okay

**Comment by Harjot1Singh** [comment]
We also want to figure out what our strategy is for showing (and bundling) release notes. Do we bundle all release notes and assets? Just the lastest? If the latest, what about the case where someone upgrades to the next minor fix after a major release, but only receives the latest, they'll miss out. Or were we planning to require an internet connection for release notes?

**Comment by bhajneet** [comment]
You could add a dropdown at the top which defaults to Latest

**Comment by saihaj** [comment]
Duplicate of #106
