### ISSUE TITLE
"Open in DB Viewer" does not work with Microsoft Edge on macOS (need to test Windows)

### ISSUE THREAD

**Issue by AkalUstat** [ShabadOS/desktop#501]

**Comment by bhajneet** [comment]
Changing to on hold, as it may be due to growing pains for new browser

**Comment by saihaj** [comment]
> Does not working in chromium edge

_Originally posted by @AkalUstat  https://github.com/ShabadOS/desktop/issues/502#issue-614926117_

**Comment by bhajneet** [comment]
It's been 2 months, can this be re-tested?

**Comment by saihaj** [comment]
Works as expected

![Kapture 2020-07-05 at 17 23 46](https://user-images.githubusercontent.com/44710980/86543463-5b314d00-bee4-11ea-8f37-6db2618d132a.gif)


**Tested on**:
Microsoft Edge: Version 83.0.478.58 (Official build) (64-bit)
ShabadOS: v2.7.0
MacOS: 10.15.5
