### ISSUE TITLE
Ability to remove lines and page numbers from translits 

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/desktop#508]
> Possible to remove the lines and numbers in the english translits?
<sub>[View in Slack](https://shabados.slack.com/archives/C013GFL7B0C/p1589205016046500)</sub>

**Comment by saihaj** [comment]
On hold since it needs ShabadOS/gurmukhi-utils#138
An option in settings for user to toggle

**Comment by bhajneet** [comment]
Can you do this for translations as well? It would have to be dynamic as we don't want to change the DB

**Comment by bhajneet** [comment]
Would go in Shabad OS > Settings > Sources as toggles

**Comment by bhajneet** [comment]
Settings > Display + Overlay

**Comment by bhajneet** [comment]
Line ending should be hidden by default

**Comment by saihaj** [comment]
@bhajneet Do we want this in 'search results' too?

**Comment by saihaj** [comment]
What icon should be used?

**Comment by bhajneet** [comment]
Perhaps this one https://fontawesome.com/icons/remove-format?style=solid

Can use any as placeholder for now

**Comment by bhajneet** [comment]
@saihaj does this apply to copy and paste as well?

**Comment by saihaj** [comment]
Nope
