### ISSUE TITLE
Explore ways to show all fields for search results

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/desktop#521]
One suggestion is to make something similar to VS-code whenever you hover your mouse over something it gets docs for that….. similarly when user hover's over they get a pop-over kinda thing that gives metadata for that line. 

![image (1)](https://user-images.githubusercontent.com/44710980/81976227-dade2200-95ed-11ea-9974-465d9a6c6e50.png)

Related to 
* https://github.com/ShabadOS/desktop/pull/510#issuecomment-628285630

**Comment by bhajneet** [comment]
Keyboard users could get a similar in-depth pop-up if they select a line and wait, esc can close pop-up

**Comment by bhajneet** [comment]
Currently no way to show english and punjabi translation at the same time on search results. Hopefully no user needs to.

Easiest would have been to simply use the radio button method of every other settings pane. However developer thought it made the settings window "looked cluttered".

Doing this much extra work to resolve this issue's end users requirements would be silly. So closing the issue, and if any user requests the ability to see english and punjabi translations at the same time from the search screen can re-open this issue if need be.

Again, hoping no one needs this requirement. Simple work around for now is to open the shabad.

When we implement these options for navigator for users that are using only the navigator window and cannot see translations, there will have to be radio buttons as initially suggested. Or a dropdown that allows multiple check boxes.

This peek suggestion is overkill.

**Comment by saihaj** [comment]
We can do it if we make or get the component in https://github.com/ShabadOS/desktop/issues/533#issuecomment-653941580
