### ISSUE TITLE
Some lines should still be truncated after 3+ lines worth

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#523]
![image](https://user-images.githubusercontent.com/14130567/82060275-28619a00-9695-11ea-8602-0b50f870fee1.png)

While I'm happy to show as much information as possible, this is actually breaking the built-in/popped-in controller. You can't even see the gurbani when using up/down arrows.

Is there a way to truncate after _n_ chars? Maybe 300 characters to test

@sarabveer I'm also wondering if these translations are aligned incorrectly? Perhaps that could resolve this issue too

**Comment by saihaj** [comment]
My suggestion is one line and truncate because  most of the search result will be consistent and if the user wants to read they can open the full shabad. Purpose is to help search in someway not to cause any confusions

**Comment by bhajneet** [comment]
There's very few over 2 lines, if you can truncate after 2 lines that's best

**Comment by bhajneet** [comment]
This should not affect gurbani or pronunciation/translits at all

**Comment by bhajneet** [comment]
Nor citation lol

Only translations should be truncated I think since we don't know how long some of them are

**Comment by saihaj** [comment]
Agreed

**Comment by saihaj** [comment]
> There's very few over 2 lines, if you can truncate after 2 lines that's best

Easy way is CSS text overflow, then we can truncate after 1 line see below. 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/44710980/82071925-61e9d380-969c-11ea-81b0-457fa0eebe4a.png">

**Comment by saihaj** [comment]
Resolution took 15 mins.
