### ISSUE TITLE
Fields not showing up properly for overlay

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#535]
If english translation is on and refreshing example overlay sometimes the english doesn't show up and you can make it show up by toggling off/on in settings (or refreshing enough times maybe)

**Comment by Harjot1Singh** [comment]
Reproduced by setting network to fast 3g

**Comment by Harjot1Singh** [comment]
https://github.com/ShabadOS/desktop/blob/dev/app/frontend/src/App.js#L89

This thing. Causes a race condition, since without setState, does not let react now the settings have updated.

**Comment by Harjot1Singh** [comment]
Reproduced on presenter too with the same conditions.

**Comment by Harjot1Singh** [comment]
TTR: 15mins
