### ISSUE TITLE
Error on opening "Sources" in Settings

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#537]
[2020-05-19_14-54-35.351Z.log](https://github.com/ShabadOS/desktop/files/4651248/2020-05-19_14-54-35.351Z.log)

* Open Shabad OS
* Click Plus Sign
* Click Settings cog
* Click "Sources" on left

![image](https://user-images.githubusercontent.com/14130567/82342367-88bb4900-99bf-11ea-9ecd-7fdf546e39bf.png)

**Comment by bhajneet** [comment]
Error repeats on reload. Only works if "Reset Settings" is clicked.

**Comment by Harjot1Singh** [comment]
https://sentry.io/organizations/shabad-os/issues/1675221595/?project=1363390&query=is%3Aunresolved

**Comment by saihaj** [comment]
I think this got fixed.... because on `dev` at f5ec302270be38eac114c22d18ad8b8bb2edb633 it is working as expected.
![shabados](https://user-images.githubusercontent.com/44710980/83975379-53689380-a8b9-11ea-83bb-a30af5dd130b.gif)
