### ISSUE TITLE
Line numbers are showing up in copying of lines when line numbers are set to hidden

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#587]
**Describe the bug**
Copying is showing line number when presenter/overlay/search is hiding the line number.

**Expected behavior**
For copy to respect what is displayed on presenter/overlay/search

**Comment by saihaj** [comment]
Not exactly sure which hidden is meant because presenter, overlay and search have their own toggles

We can either use presenter toggle value (Maybe that is what you meant) or add this as a long press hotkey combination  (https://github.com/ShabadOS/desktop/issues/352)

**Comment by saihaj** [comment]
Can be a good candidate for long press hotkeys #352

**Comment by bhajneet** [comment]
Don't need an alternate hotkey, but a fix to the current hotkey. If someone
copies a line and there is no line ending shown, then there should be no
line ending copied.

**Comment by saihaj** [comment]
Fixing this based on value of presenter setting
