### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#75]
Predefined layouts: choose what's displayed, font sizes, font colours, positioning, themes, possibly display configuration.

**Comment by bhajneet** [comment]
Can you expand on this? Is it similar to the idea of "scenes"?

Scene 1 can have specific fields shown in various ordering, different font sizes/colors for those fields, margin/padding for the presenter, overall theme for colors/bg

Scene 2 can have the same

Different (connected) displays can choose which scene to apply?

**Comment by Harjot1Singh** [comment]
Yeah, similar.

**Comment by Sarabveer** [comment]
Need to implement independent font sizes for each line (Gurbani, English Translit, Punjabi Translit, Transliteration)

**Comment by bhajneet** [comment]
A better method would be to keep one font-slider for the base font size and implement ratios for the individual lines. Each slider should show a value.

Example:

Base slider = 1vh
Gurbani slider = 1.25 x Base
English slider = .8 x Base

User sees 1vh Base, x1.25 Gurbani, x0.8 English

Sliding the "base" will change both Gurbani and English by respective ratios, maintaining the gurbani to english sizing ratio.

Sliding just the English will make it bigger or smaller the way you'd already expect.

**Comment by swissarmykirpan** [comment]
@bhajneet do we have any mockups of what this would look like?

**Comment by bhajneet** [comment]
This is how I envision it. Basically you have a master font size in vh (vertical height units) and then you have all the sliders for any potentially visible field as a relative slider.

It might make more sense to hide the slider unless it's activated. It would also look nicer if the sliders and toggles were left aligned properly.

The current font slider is in the wrong tab (Theme), I think it makes more sense to be in the Layout tab.

![Untitled-1](https://user-images.githubusercontent.com/14130567/65066903-50a4c780-d953-11e9-847c-0c7466b9ec23.png)

**Comment by bhajneet** [comment]
Also, for Tier 1 in Kanban, we literally only need the font size slider to work. All the extra relative fonts can be added in at different time.
