### ISSUE TITLE
Error while setting up

### ISSUE THREAD

**Issue by sbaljeet13** [ShabadOS/desktop#83]
I forked this project and trying to set it up on Windows. 

I ran `npm install` and it gave errors so I ran `npm install --global --production windows-build-tools` and it also give errors at `node-pre-gyp` and following lines are from the log:

70 error code ELIFECYCLE
71 error errno 1
72 error @shabados/desktop@0.0.1 postinstall: `npm run install-deps && electron-builder install-app-deps`
72 error Exit status 1
73 error Failed at the @shabados/desktop@0.0.1 postinstall script.
73 error This is probably not a problem with npm. There is likely additional logging output above.
74 verbose exit [ 1, true ]

Not sure what is the problem. Any help?

PS: What is the better way to contact someone about this project?

Thanks

**Comment by Harjot1Singh** [comment]
WJKK WJKF!

What version of npm are you on? Are there any proceeding error messages that might be helpful to what you pasted?

You can also join our public slack at https://slack.shabados.com so we can talk it out :)

**Comment by Harjot1Singh** [comment]
Resolved by installing VS 2015 tools, using `npm install -g windows-build-tools -vs2015`
