### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#92]
When the `Configurator` component is added as a `Route` within a `Switch`, the `Display` and `Controller` begin to lag...

I suspect that server updates cause too many top-down render cycles, since state is propagated all the way downwards?

**Comment by Harjot1Singh** [comment]
Returning `false` in `shouldComponentUpdate()` of `Configurator` fixes it. Not sure why this should be the case when it should not be rendered. Perhaps using the `render` method of `Route` is not the right choice?

**Comment by Harjot1Singh** [comment]
I think this is a red-herring... Production builds seem perfectly fine, must be dev React causing this.

**Comment by bhajneet** [comment]
Can close and monitor production builds. Is there any test we can do on
prod?

**Comment by Harjot1Singh** [comment]
No tests really, the performance difference was noticeable on my monster machine, the best thing to do to confirm is try it on a laptop with poor graphics and compare to old Shabad OS.

**Comment by bhajneet** [comment]
I don't see a build to test with on CircleCI. The configurator branch
failed due to lint.

My test would be on the integrated graphics for an 8th gen intel i7.

Others can test if a build is available.

**Comment by Harjot1Singh** [comment]
See https://github.com/mui-org/material-ui/issues/10778

**Comment by Harjot1Singh** [comment]
We should also consider using virtualised lists for banis, and measure how long it takes for longer banis such as Sukhmani Sahib to actually load from DB and into the viewer

**Comment by bhajneet** [comment]
Virtualized bani performance should be a separate issue

**Comment by bhajneet** [comment]
@Harjot1Singh updates? I believe this should be closed. A new issue for virtualized bani performance was created under Alpha 2 milestone as issue #143

**Comment by Harjot1Singh** [comment]
Can be closed, no issues here
