### ISSUE TITLE
Add option in settings to store db in ram

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#99]
See https://github.com/ShabadOS/database/issues/96

**Comment by Harjot1Singh** [comment]
Maybe it should be on by default for machines with >= 4GB?

**Comment by bhajneet** [comment]
How much ram does it take up?

**Comment by Harjot1Singh** [comment]
Maximum of DB size, so ~150MB, but I think machines <3GB might be constrained already, so running Shabad OS + loading DB could be 500MB of RAM.

**Comment by bhajneet** [comment]
Then, yes, it can be default for machines with minimum 4 gb ram

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
